# Generated by Django 5.2.6 on 2025-09-16 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Conquista')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(help_text="Ex: 'fa-trophy'", max_length=100, verbose_name='Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cômodo')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comodos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos de Experiência')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nível')),
                ('streak_atual', models.IntegerField(default=0, verbose_name='Sequência Atual (dias)')),
                ('data_ultima_atividade', models.DateField(blank=True, null=True, verbose_name='Data da Última Atividade')),
                ('conquistas', models.ManyToManyField(blank=True, to='gestao.conquista')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('frequencia', models.CharField(max_length=100, verbose_name='Quando Fazer / Frequência')),
                ('data_ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='gestao.comodo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Conclusão')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='gestao.tarefa')),
            ],
        ),
    ]
